{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Lab 11 cnn_basics"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%matplotlib inline\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /var/folders/fj/y92l0p5x6d9030lr98_z9d2r0000gn/T/ipykernel_17665/1601395567.py:1: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.\n",
      "\n",
      "(1, 3, 3, 1)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-08-18 08:16:32.754645: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2\n",
      "To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-08-18 08:16:32.757787: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<matplotlib.image.AxesImage at 0x7fd218de7160>"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAQ8AAAD8CAYAAABpXiE9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAANqElEQVR4nO3df6jd9X3H8edrGkWsI7poTWNaWwiTTuiaXVI7x8hYLRqEFFpG/KOKDC6KQgv1j1Ch/Wuw7Y/CXIpZoFKFovvD1oYtXWelTPuHzhgSY7SuiRO8JphqTVRaqHHv/XG/bpfrubn3fs73nnOSPh9wON8fn/N9v/0or3zP93y/JlWFJC3X7427AUlnJsNDUhPDQ1ITw0NSE8NDUhPDQ1KTc4f5cJJLgH8GrgReBv6qqt4cMO5l4G3gPeBUVU0NU1fS+A175rEdeKyqNgCPdesL+Yuq+mODQzo7DBseW4H7u+X7gS8MeTxJZ4gMc4dpkhNVtXrO+ptVdfGAcf8NvAkU8E9Vtes0x5wGpgEuvPDCP7nqqqua+zvbvffee+NuYeK9++67425hor366qu8+eabafnsotc8kvwEuHzArruXUefaqjqa5DLg0SQ/r6rHBw3sgmUXwNTUVO3du3cZZX63nDhxYtwtTLzXXntt3C1MtC9+8YvNn100PKrqcwvtS/JakrVVdSzJWuD4Asc42r0fT/IDYBMwMDwknRmGveaxG7ilW74F+OH8AUkuTHLR+8vA54HnhqwracyGDY+/Ba5L8gvgum6dJB9Jsqcb82HgZ0kOAP8J/GtV/duQdSWN2VD3eVTVG8BfDth+FNjSLb8EfGqYOpImj3eYSmpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIatJLeCS5PsmLSQ4n2T5gf5Lc0+1/NsnGPupKGp+hwyPJOcC3gRuATwI3JfnkvGE3ABu61zRw77B1JY1XH2cem4DDVfVSVf0WeAjYOm/MVuCBmvUksDrJ2h5qSxqTPsJjHfDKnPWZbttyx0g6g/QRHhmwrRrGzA5MppPsTbL3l7/85dDNSVoZfYTHDLB+zvoVwNGGMQBU1a6qmqqqqUsvvbSH9iSthD7C42lgQ5KPJzkP2AbsnjdmN3Bz96vLNcDJqjrWQ21JY3LusAeoqlNJ7gR+DJwD3FdVh5Lc1u3fCewBtgCHgV8Dtw5bV9J4DR0eAFW1h9mAmLtt55zlAu7oo5akyeAdppKaGB6SmhgekpoYHpKaGB6SmhgekpoYHpKaGB6SmhgekpoYHpKaGB6SmhgekpoYHpKaGB6SmhgekpoYHpKaGB6SmhgekpoYHpKaGB6SmhgekpoYHpKaGB6SmhgekpoYHpKaGB6SmhgekpoYHpKa9BIeSa5P8mKSw0m2D9i/OcnJJPu71zf6qCtpfM4d9gBJzgG+DVwHzABPJ9ldVc/PG/pEVd04bD1Jk6GPM49NwOGqeqmqfgs8BGzt4biSJtjQZx7AOuCVOeszwGcGjPtskgPAUeCuqjo06GBJpoFpgMsuu4zHHnushxbPTi+++OK4W5h4R44cGXcLE+31119v/mwfZx4ZsK3mre8DPlZVnwL+EXhkoYNV1a6qmqqqqdWrV/fQnqSV0Ed4zADr56xfwezZxf+pqreq6p1ueQ+wKsmaHmpLGpM+wuNpYEOSjyc5D9gG7J47IMnlSdItb+rqvtFDbUljMvQ1j6o6leRO4MfAOcB9VXUoyW3d/p3Al4Dbk5wCfgNsq6r5X20knUH6uGD6/leRPfO27ZyzvAPY0UctSZPBO0wlNTE8JDUxPCQ1MTwkNTE8JDUxPCQ1MTwkNTE8JDUxPCQ1MTwkNTE8JDUxPCQ1MTwkNTE8JDUxPCQ1MTwkNTE8JDUxPCQ1MTwkNTE8JDUxPCQ1MTwkNTE8JDUxPCQ1MTwkNTE8JDUxPCQ16SU8ktyX5HiS5xbYnyT3JDmc5NkkG/uoK2l8+jrz+C5w/Wn23wBs6F7TwL091ZU0Jr2ER1U9DvzqNEO2Ag/UrCeB1UnW9lFb0niM6prHOuCVOesz3bYPSDKdZG+SvSdOnBhFb5IajCo8MmBbDRpYVbuqaqqqplavXr2yXUlqNqrwmAHWz1m/Ajg6otqSVsCowmM3cHP3q8s1wMmqOjai2pJWwLl9HCTJg8BmYE2SGeCbwCqAqtoJ7AG2AIeBXwO39lFX0vj0Eh5VddMi+wu4o49akiaDd5hKamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhqYnhIamJ4SGpieEhq0kt4JLkvyfEkzy2wf3OSk0n2d69v9FFX0vj08hddA98FdgAPnGbME1V1Y0/1JI1ZL2ceVfU48Ks+jiXpzNDXmcdSfDbJAeAocFdVHRo0KMk0MA1wwQUXsGPHjhG2eGY5ePDguFuYeEeOHBl3C2etUYXHPuBjVfVOki3AI8CGQQOrahewC+Diiy+uEfUnaZlG8mtLVb1VVe90y3uAVUnWjKK2pJUxkvBIcnmSdMuburpvjKK2pJXRy9eWJA8Cm4E1SWaAbwKrAKpqJ/Al4PYkp4DfANuqyq8k0hmsl/CoqpsW2b+D2Z9yJZ0lvMNUUhPDQ1ITw0NSE8NDUhPDQ1ITw0NSE8NDUhPDQ1ITw0NSE8NDUhPDQ1ITw0NSE8NDUhPDQ1ITw0NSE8NDUhPDQ1ITw0NSE8NDUhPDQ1ITw0NSE8NDUhPDQ1ITw0NSE8NDUhPDQ1ITw0NSk6HDI8n6JD9N8kKSQ0m+MmBMktyT5HCSZ5NsHLaupPHq4y+6PgV8rar2JbkIeCbJo1X1/JwxNwAbutdngHu7d0lnqKHPPKrqWFXt65bfBl4A1s0bthV4oGY9CaxOsnbY2pLGp9drHkmuBD4NPDVv1zrglTnrM3wwYCSdQfr42gJAkg8BDwNfraq35u8e8JFa4DjTwDTABRdc0Fd7knrWy5lHklXMBsf3qur7A4bMAOvnrF8BHB10rKraVVVTVTV1/vnn99GepBXQx68tAb4DvFBV31pg2G7g5u5Xl2uAk1V1bNjaksanj68t1wJfBg4m2d9t+zrwUYCq2gnsAbYAh4FfA7f2UFfSGA0dHlX1MwZf05g7poA7hq0laXJ4h6mkJoaHpCaGh6QmhoekJoaHpCaGh6QmhoekJoaHpCaGh6QmhoekJoaHpCaGh6QmhoekJoaHpCaGh6QmhoekJoaHpCaGh6QmhoekJoaHpCaGh6QmhoekJoaHpCaGh6QmhoekJoaHpCaGh6QmhoekJkOHR5L1SX6a5IUkh5J8ZcCYzUlOJtnfvb4xbF1J43VuD8c4BXytqvYluQh4JsmjVfX8vHFPVNWNPdSTNAGGPvOoqmNVta9bfht4AVg37HElTbZUVX8HS64EHgeurqq35mzfDDwMzABHgbuq6tACx5gGprvVq4HnemtweGuA18fdxBz2s7hJ62nS+vnDqrqo5YO9hUeSDwH/AfxNVX1/3r7fB/6nqt5JsgX4h6rasIRj7q2qqV4a7IH9nN6k9QOT19PZ1E8vv7YkWcXsmcX35gcHQFW9VVXvdMt7gFVJ1vRRW9J49PFrS4DvAC9U1bcWGHN5N44km7q6bwxbW9L49PFry7XAl4GDSfZ3274OfBSgqnYCXwJuT3IK+A2wrZb2fWlXD/31yX5Ob9L6gcnr6azpp9cLppJ+d3iHqaQmhoekJhMTHkkuSfJokl907xcvMO7lJAe729z3rkAf1yd5McnhJNsH7E+Se7r9zybZ2HcPDT2N7Pb/JPclOZ5k4P03Y5qfxXoa6eMRS3xkY2TztGKPkFTVRLyAvwe2d8vbgb9bYNzLwJoV6uEc4AjwCeA84ADwyXljtgA/AgJcAzy1wvOylJ42A/8yon9Pfw5sBJ5bYP9I52eJPY1sfrp6a4GN3fJFwH+N87+jJfaz7DmamDMPYCtwf7d8P/CFMfSwCThcVS9V1W+Bh7q+5toKPFCzngRWJ1k75p5GpqoeB351miGjnp+l9DRStbRHNkY2T0vsZ9kmKTw+XFXHYPYfFrhsgXEF/HuSZ7pb2fu0DnhlzvoMH5zkpYwZdU8An01yIMmPkvzRCvazmFHPz1KNZX66RzY+DTw1b9dY5uk0/cAy56iP+zyWLMlPgMsH7Lp7GYe5tqqOJrkMeDTJz7s/efqQAdvm/5a9lDF9Wkq9fcDH6v9v/38EWPT2/xUy6vlZirHMT/fIxsPAV2vOs17v7x7wkRWdp0X6WfYcjfTMo6o+V1VXD3j9EHjt/dO27v34Asc42r0fB37A7Gl9X2aA9XPWr2D2Qb7ljunTovVqsm7/H/X8LGoc87PYIxuMeJ5W4hGSSfrashu4pVu+Bfjh/AFJLszs/zOEJBcCn6ffp26fBjYk+XiS84BtXV/z+7y5u1p+DXDy/a9bK2TRnjJZt/+Pen4WNer56Wqd9pENRjhPS+mnaY5W8qrzMq8I/wHwGPCL7v2SbvtHgD3d8ieY/bXhAHAIuHsF+tjC7NXoI+8fH7gNuK1bDvDtbv9BYGoEc7NYT3d283EAeBL40xXs5UHgGPAus396/vUEzM9iPY1sfrp6f8bsV5Bngf3da8u45mmJ/Sx7jrw9XVKTSfraIukMYnhIamJ4SGpieEhqYnhIamJ4SGpieEhq8r+pTw4icY2ilQAAAABJRU5ErkJggg==",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "sess = tf.InteractiveSession()\n",
    "image = np.array([[[[1],[2],[3]],\n",
    "                   [[4],[5],[6]], \n",
    "                   [[7],[8],[9]]]], dtype=np.float32)\n",
    "print(image.shape)\n",
    "plt.imshow(image.reshape(3,3), cmap='Greys')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1 filter (2,2,1,1) with padding: VALID\n",
    "\n",
    "weight.shape = 1 filter (2 , 2 , 1, 1)\n",
    "\n",
    "<img width=\"1060\" alt=\"스크린샷 2022-08-18 오전 8 06 06\" src=\"https://user-images.githubusercontent.com/91893721/185258897-8f25f9d0-c75d-4a03-bb53-fbb0930b8ccd.png\">"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "image.shape (1, 3, 3, 1)\n",
      "weight.shape (2, 2, 1, 1)\n",
      "conv2d_img.shape (1, 2, 2, 1)\n",
      "[[12. 16.]\n",
      " [24. 28.]]\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAM0AAAC7CAYAAADGxxq1AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAI4klEQVR4nO3dTYhd9RnH8e9Tqxu1WhuS+IYvMApWaEmHNFaoU1pFgxAXUuLGIIWg6LKLQMB22ZZuKhFlFtJko11VQzu2vkDRLtI6ivGlaE0lYEio1JYxQcWkfbq4J+10eiczT+6Zc+7E7weGe+49/3v+D0d+Oece//BEZiJp+T7XdwHSamNopCJDIxUZGqnI0EhFhkYq+vwoX46Ii4BfAFcCB4HvZuY/how7CBwF/gmcyMzJUeaV+jTqlWYH8HxmTgDPN+8X863M/KqB0Wo3ami2ALub7d3AHSMeTxp7o4ZmXWYeAWhe1y4yLoFnIuLliNg+4pxSr5b8TRMRzwHrh+zaWZjnxsw8HBFrgWcj4q3MfGGR+bYDJ4P1tcIcn3nnnXde3yWsKp988gnHjx+P6vdilLVnEfE2MJWZRyLiYuB3mXntEt/5IXAsM3+6jOO7MK5gamqq7xJWldnZWY4ePVoOzai3Z3uBbc32NuCphQMi4tyIOP/kNnAL8MaI80q9GTU0PwJujoh3gJub90TEJREx04xZB/w+IvYDfwR+nZm/GXFeqTcj/X+azPwA+PaQzw8Dm5vtd4GvjDKPNE5cESAVGRqpyNBIRYZGKjI0UpGhkYoMjVRkaKQiQyMVGRqpyNBIRYZGKjI0UpGhkYoMjVRkaKQiQyMVGRqpyNBIRYZGKjI0UpGhkYoMjVRkaKQiQyMVGRqpyNBIRYZGKjI0UlEroYmIWyPi7Yg4EBH/16w2Bh5q9r8WERvamFfqw8ihiYizgIeB24DrgLsi4roFw24DJpq/7cAjo84r9aWNK81G4EBmvpuZnwJPMOj6PN8WYE8O7AMubNoNSqtOG6G5FHhv3vtDzWfVMdKqMFIntMawRp8LG8wuZ8xg4P92d5bGThuhOQRcPu/9ZcDh0xgDQGZOA9Ngd2eNpzZuz14CJiLiqog4B9jKoOvzfHuBu5unaJuAucw80sLcUudGvtJk5omIeAD4LXAW8FhmvhkR9zb7HwVmGDSuPQB8BNwz6rxSX9q4PSMzZxgEY/5nj87bTuD+NuaS+uaKAKnI0EhFhkYqMjRSkaGRigyNVGRopCJDIxUZGqnI0EhFhkYqMjRSkaGRigyNVGRopCJDIxUZGqnI0EhFhkYqMjRSkaGRigyNVGRopCJDIxUZGqnI0EhFhkYqMjRSkaGRirrq7jwVEXMR8Wrz92Ab80p9GLnVxrzuzjcz6Hj2UkTszcw/LRj6YmbePup8Ut+66u4snTHaaOo0rHPz14eMuyEi9jPotfn9zHxzqQNfc801TE9Pt1DiZ8NNN93UdwmryuTk5Gl9r6vuzq8AV2TmsYjYDDwJTAw92LzuzuvWrWuhPKldbdyeLdm5OTM/zMxjzfYMcHZErBl2sMyczszJzJy84IILWihPalcn3Z0jYn1ERLO9sZn3gxbmljrXVXfnO4H7IuIE8DGwtWleK606XXV33gXsamMuqW+uCJCKDI1UZGikIkMjFRkaqcjQSEWGRioyNFKRoZGKDI1UZGikIkMjFRkaqcjQSEWGRioyNFKRoZGKDI1UZGikIkMjFRkaqcjQSEWGRioyNFKRoZGKDI1UZGikIkMjFRkaqait7s6PRcT7EfHGIvsjIh5quj+/FhEb2phX6kNbV5qfA7eeYv9tDNoFTjBoDfhIS/NKnWslNJn5AvD3UwzZAuzJgX3AhRFxcRtzS13r6jfNsA7Ql3Y0t9SqrkKznA7Qg4ER2yNiNiJm5+bmVrgsqa6r0CzZAfokuztr3HUVmr3A3c1TtE3AXGYe6WhuqVWtNKqNiMeBKWBNRBwCfgCcDf9pWDsDbAYOAB8B97Qxr9SHtro737XE/gTub2MuqW+uCJCKDI1UZGikIkMjFRkaqcjQSEWGRioyNFKRoZGKDI1UZGikIkMjFRkaqcjQSEWGRioyNFKRoZGKDI1UZGikIkMjFRkaqcjQSEWGRioyNFKRoZGKDI1UZGikIkMjFRkaqair7s5TETEXEa82fw+2Ma/Uh1ZabTDo7rwL2HOKMS9m5u0tzSf1pqvuztIZo8vfNDdExP6IeDoivtzhvFKrYtCkrIUDRVwJ/Cozrx+y7wvAvzLzWERsBn6WmROLHGc7sL15ez0w9HdSz9YAf+u7iCGsq+bazDy/+qVOQjNk7EFgMjNPeSIjYjYzJ1spsEXWVXOm1dXJ7VlErI+IaLY3NvN+0MXcUtu66u58J3BfRJwAPga2ZluXOKljXXV33sXgkXTV9OlVtOKsq+aMqqu13zTSZ4XLaKSisQlNRFwUEc9GxDvN6xcXGXcwIl5vluPMrmA9t0bE2xFxICJ2DNkfEfFQs/+1iNiwUrUU6+plydIyllL1db7aX+KVmWPxB/wE2NFs7wB+vMi4g8CaFa7lLOAvwNXAOcB+4LoFYzYDTwMBbAL+0ME5Wk5dUwwe/Xf93++bwAbgjUX2d36+lllX+XyNzZUG2ALsbrZ3A3f0VwobgQOZ+W5mfgo8waC++bYAe3JgH3BhRFw8BnX1IpdeStXH+VpOXWXjFJp1mXkEoHldu8i4BJ6JiJeb1QMr4VLgvXnvDzWfVcf0UReM55KlPs7XcpXOV1urnJclIp4D1g/ZtbNwmBsz83BErAWejYi3mn9N2hRDPlv4mHE5Y9q2nDlfAa7I/y5ZehIYumSpY32cr+Uon69OrzSZ+Z3MvH7I31PAX09erpvX9xc5xuHm9X3glwxuWdp2CLh83vvLgMOnMabzujLzw8w81mzPAGdHxJoVrms5+jhfSzqd8zVOt2d7gW3N9jbgqYUDIuLciDj/5DZwCyuzoPMlYCIiroqIc4CtTX0L6727eSq0CZg7eXu5gpasa4yXLPVxvpZ0Wuer66csp3jK8SXgeeCd5vWi5vNLgJlm+2oGT4z2A28CO1ewns3Anxk8rdrZfHYvcG+zHcDDzf7XGSxA7eI8LVXXA8252Q/sA77RUV2PA0eA4wyuKt8bk/O1VF3l8+WKAKlonG7PpFXB0EhFhkYqMjRSkaGRigyNVGRopCJDIxX9G43Agyd6ViA+AAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "# print(\"imag:\\n\", image)\n",
    "print(\"image.shape\", image.shape)\n",
    "weight = tf.constant([[[[1.]],[[1.]]],\n",
    "                      [[[1.]],[[1.]]]])\n",
    "print(\"weight.shape\", weight.shape)\n",
    "conv2d = tf.nn.conv2d(image, weight, strides=[1, 1, 1, 1], padding='VALID')\n",
    "conv2d_img = conv2d.eval()\n",
    "print(\"conv2d_img.shape\", conv2d_img.shape)\n",
    "conv2d_img = np.swapaxes(conv2d_img, 0, 3)\n",
    "for i, one_img in enumerate(conv2d_img):\n",
    "    print(one_img.reshape(2,2))\n",
    "    plt.subplot(1,2,i+1), plt.imshow(one_img.reshape(2,2), cmap='gray')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1 filter (2,2,1,1) with padding:SAME\n",
    "\n",
    "\n",
    "<img width=\"1044\" alt=\"스크린샷 2022-08-18 오전 8 07 36\" src=\"https://user-images.githubusercontent.com/91893721/185259011-b849337c-186f-4421-9c07-e00aacbb336c.png\">"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "image.shape (1, 3, 3, 1)\n",
      "weight.shape (2, 2, 1, 1)\n",
      "conv2d_img.shape (1, 3, 3, 1)\n",
      "[[12. 16.  9.]\n",
      " [24. 28. 15.]\n",
      " [15. 17.  9.]]\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAMUAAAC7CAYAAADVEFpBAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJV0lEQVR4nO3dcaiddR3H8fcnnWMsY8bSu6Y5/7gIFlh2vSpCrGLhhjD/kNj+SJHg0phQkH9IgfVP0h8RZAtlkOSF0IJijbplJi0VsnYdmzltdRHB4UC65uZQlFvf/nie2eG7c3fv3fN7nnO2+3nB4T7neX73fH+Hez885zznOd9HEYGZ/d8HBj0Bs2HjUJglDoVZ4lCYJQ6FWeJQmCUXNvllSR8GfgZsAF4BvhgR/+4z7hXgLeA/wFxEjDWpa9ampnuKe4EnI2IUeLK+P5/PRsQnHQgbdk1DsRV4pF5+BLit4eOZDVzTUFwWEccA6p+XzjMugN9Lek7SRMOaZq1a8D2FpD8AI302fXMJdW6OiNckXQo8IenvEfHUPPUmgIl6+dMrV65cQpnhtXr16kFPoZjZ2dlBT6GYiFBepybnPkk6AmyMiGOS1gH7IuLqBX7n28DJiPjeQo+/atWq2LBhw1nPb5iMj48PegrFTE5ODnoKxfQLRdOXT3uBO+vlO4Ff5QGSVku6+NQy8AXghYZ1zVrTNBTfBTZJ+iewqb6PpI9KmqrHXAY8I+kQ8FfgNxHxu4Z1zVrT6HOKiJgFPt9n/WvAlnr5ZeDaJnXMuuRPtM0Sh8IscSjMEofCLHEozBKHwixxKMwSh8IscSjMEofCLHEozBKHwixxKMwSh8IscSjMEofCLHEozJIioZB0i6QjkmYkndYQTZUH6u3PS7quRF2zNjQOhaQLgB8Bm4FrgO2SrknDNgOj9W0CeLBpXbO2lNhTjAMzEfFyRLwHPEbVObDXVmAyKs8Ca+qWOGZDp0Qo1gOv9tw/Wq9b6higaoYmaVrS9NzcXIHpmS1NiVCc1kyKqk3mUsdUKyN2R8RYRIxdeGGjZiNmZ6VEKI4CV/Tcvxx47SzGmA2FEqHYD4xKukrSRcA2qs6BvfYCd9RHoW4Ejp9qzGw2bBq/PomIOUl3A48DFwAPR8RhSV+ptz8ETFE1R5sB3gbualrXrC1FXrRHxBTVP37vuod6lgPYWaKWWdv8ibZZ4lCYJQ6FWeJQmCUOhVniUJglDoVZ4lCYJQ6FWeJQmCUOhVniUJglDoVZ4lCYJQ6FWeJQmCVdNUPbKOm4pIP17b4Sdc3a0Pibdz3N0DZRNSjYL2lvRLyYhj4dEbc2rWfWtq6aoZmdM0p8R7tfo7Mb+oy7SdIhqtY290TE4X4PJmmCqrUmIyMjTE5OFpji4F1//fWDnkIxJ06cGPQUiti3b1/f9V01QzsAXBkR1wI/BPbM92C9zdDWrFlTYHpmS9NJM7SIOBERJ+vlKWCFpLUFapsV10kzNEkjklQvj9d1ZwvUNiuuq2ZotwM7JM0B7wDb6l5QZkOnq2Zou4BdJWqZtc2faJslDoVZ4lCYJQ6FWeJQmCUOhVniUJglDoVZ4lCYJQ6FWeJQmCUOhVniUJglDoVZ4lCYJQ6FWVKqGdrDkl6X9MI82yXpgbpZ2vOSritR16wNpfYUPwFuOcP2zcBofZsAHixU16y4IqGIiKeAN84wZCswGZVngTWS1pWobVZaV+8p+jVMW99RbbMl6SoUi2mYVg2UJiRNS5p+8803252VWR9dhWLBhmmnuEOgDVpXodgL3FEfhboROB4RxzqqbbYkRfo+SXoU2AislXQU+BawAt7v/zQFbAFmgLeBu0rUNWtDqWZo2xfYHsDOErXM2uZPtM0Sh8IscSjMEofCLHEozBKHwixxKMwSh8IscSjMEofCLHEozBKHwixxKMwSh8IscSjMEofCLHEozJKuOgRulHRc0sH6dl+JumZtKPJ1VKoOgbuAyTOMeToibi1Uz6w1XXUINDtnlNpTLMZNkg5R9Xu6JyIO9xskaYKq3yyrVq3i/vvv73CK7Vm//vxpiLhnz55BT6FVXYXiAHBlRJyUtAXYQ9Vs+TQRsRvYDXDJJZf07SJo1qZOjj5FxImIOFkvTwErJK3torbZUnUSCkkjklQvj9d1Z7uobbZUXXUIvB3YIWkOeAfYVjdIMxs6XXUI3EV1yNZs6PkTbbPEoTBLHAqzxKEwSxwKs8ShMEscCrPEoTBLHAqzxKEwSxwKs8ShMEscCrPEoTBLHAqzxKEwSxqHQtIVkv4o6SVJhyV9tc8YSXpA0oyk5yVd17SuWVtKfPNuDvh6RByQdDHwnKQnIuLFnjGbqbp3jAI3AA/WP82GTuM9RUQci4gD9fJbwEtAbnK0FZiMyrPAGknrmtY2a0PR9xSSNgCfAv6SNq0HXu25f5TTg3PqMSYkTUuafvfdd0tOz2xRioVC0geBXwBfi4gTeXOfX+nbzSMidkfEWESMrVy5stT0zBatVNfxFVSB+GlE/LLPkKPAFT33L6dqn2k2dEocfRLwY+CliPj+PMP2AnfUR6FuBI5HxLGmtc3aUOLo083Al4C/STpYr/sG8DF4vxnaFLAFmAHeBu4qUNesFY1DERHP0P89Q++YAHY2rWXWBX+ibZY4FGaJQ2GWOBRmiUNhljgUZolDYZY4FGaJQ2GWOBRmiUNhljgUZolDYZY4FGaJQ2GWOBRmSVfN0DZKOi7pYH27r2lds7Z01QwN4OmIuLVAPbNWddUMzeyc0VUzNICbJB2S9FtJHy9Z16wkVT0FCjxQ1QztT8B3cu8nSR8C/hsRJyVtAX4QEaPzPM4EMFHfvRo4UmSC81sL/KvlGl05X55LV8/jyoj4SF5ZJBR1M7RfA4+fofdT7/hXgLGIGPgfUNJ0RIwNeh4lnC/PZdDPo5NmaJJG6nFIGq/rzjatbdaGrpqh3Q7skDQHvANsi1Kv28wK66oZ2i5gV9NaLdk96AkUdL48l4E+j2JvtM3OFz7NwyxZtqGQdIukI/V1+O4d9HyakPSwpNclvTDouTSxmFOGOpnHcnz5JOkC4B/AJqprZ+wHtvc5NeWcIOkzwEmqS6h9YtDzOVv1Jd/W9Z4yBNzW9d9lue4pxoGZiHg5It4DHqO6Lt85KSKeAt4Y9DyaGpZThpZrKBZ9DT4bjAVOGWrVcg3Foq/BZ91b4PqJrVuuofA1+IbUIq6f2LrlGor9wKikqyRdBGyjui6fDdAir5/YumUZioiYA+4GHqd6M/fziDg82FmdPUmPAn8GrpZ0VNKXBz2ns3TqlKHP9XxLc0vXk1iWh2TNzmRZ7inMzsShMEscCrPEoTBLHAqzxKEwSxwKs8ShMEv+Bzu1/mezy32sAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "# print(\"imag:\\n\", image)\n",
    "print(\"image.shape\", image.shape)\n",
    "\n",
    "weight = tf.constant([[[[1.]],[[1.]]],\n",
    "                      [[[1.]],[[1.]]]])\n",
    "print(\"weight.shape\", weight.shape)\n",
    "conv2d = tf.nn.conv2d(image, weight, strides=[1, 1, 1, 1], padding='SAME')\n",
    "conv2d_img = conv2d.eval()\n",
    "print(\"conv2d_img.shape\", conv2d_img.shape)\n",
    "conv2d_img = np.swapaxes(conv2d_img, 0, 3)\n",
    "for i, one_img in enumerate(conv2d_img):\n",
    "    print(one_img.reshape(3,3))\n",
    "    plt.subplot(1,2,i+1), plt.imshow(one_img.reshape(3,3), cmap='gray')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3 filters (2,2,1,3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "image.shape (1, 3, 3, 1)\n",
      "weight.shape (2, 2, 1, 3)\n",
      "conv2d_img.shape (1, 3, 3, 3)\n",
      "[[12. 16.  9.]\n",
      " [24. 28. 15.]\n",
      " [15. 17.  9.]]\n",
      "[[120. 160.  90.]\n",
      " [240. 280. 150.]\n",
      " [150. 170.  90.]]\n",
      "[[-12. -16.  -9.]\n",
      " [-24. -28. -15.]\n",
      " [-15. -17.  -9.]]\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAWoAAACBCAYAAADpLPAWAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAHUklEQVR4nO3dwWtdZR7G8eeZJu2iGnrpzEKuZeJQEbpTbrMRhuKq48atLtKN0FVAYTb+EcVdNwVLCYgi1YULQWZhEUGsd4oD7QSHju1gUHBaWyJdVAK/WeQyk8HU3DTnPe+vb74fCOQm5Zzn5ikPJ4ebxBEhAEBev6kdAADw6xhqAEiOoQaA5BhqAEiOoQaA5GaKHHRmJmZnZ0scemoHDx6sen5Jun37du0Iigh3dSx63dBar4PBIIbDYVeHeyj37t2ren5JOnz4cNXz37x5U7du3dqy1yJDPTs7q/n5+RKHntrCwkLV80vS8vJy7QidotcNrfU6HA518eLFqhkuX75c9fySdOrUqarnH41GD/wctz4AIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCSm2qobZ+0/bXt67bfKB0K/aDXNtFre7Ydatv7JJ2V9CdJxyS9YvtY6WAoi17bRK9tmuaKekHS9Yj4JiJ+lvSupJfKxkIP6LVN9NqgaYZ6KOnbTY9XJx/7P7ZP2x7bHq+vr3eVD+XQa5t23OudO3d6C4eHM81Qb/UXB+IXH4g4FxGjiBjNzBT5ewToFr22ace9DgaDHmJhN6YZ6lVJRzY9flLSd2XioEf02iZ6bdA0Q/2lpKdtP2V7v6SXJX1YNhZ6QK9totcGbfu9bESs216S9LGkfZLOR8S14slQFL22iV7bNNVNx4j4SNJHhbOgZ/TaJnptDz+ZCADJMdQAkBxDDQDJMdQAkBxDDQDJMdQAkBxDDQDJMdQAkBxDDQDJMdQAkFyR31s5Pz+v5eXlEoee2vHjx6ueX5LW1taqnv/SpUudHo9eN7TW640bN7S4uNjpMXdqPB5XPb8kzc3NVT3/3bt3H/g5rqgBIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCS23aobZ+3/YPtq30EQj/otV10255prqgvSDpZOAf6d0H02qoLotumbDvUEfGppB97yIIe0Wu76LY93KMGgOQ6G2rbp22PbY9/7Rdg49FCr23a3Ov6+nrtONhGZ0MdEeciYhQRo0OHDnV1WFRGr23a3OvMTJE/9IQOcesDAJKb5uV570j6XNIztldtv1o+Fkqj13bRbXu2/Z4nIl7pIwj6Ra/totv2cOsDAJJjqAEgOYYaAJJjqAEgOYYaAJJjqAEgOYYaAJJjqAEgOYYaAJJjqAEgOYYaAJJzRHR+0MFgECdOnOj8uDsxHA6rnl+Szp49WzuCIsJdHYteN7TW69GjR+PMmTNdHe6hrK6uVj2/JC0tLVU9/2g00ng83rJXrqgBIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCSY6gBIDmGGgCS23aobR+x/YntFdvXbL/WRzCURa9totc2zUzxb9Yl/Tkirth+XNJfbf8lIv5eOBvKotc20WuDtr2ijojvI+LK5P2fJK1Iqv+7JrEr9Nomem3Tju5R256X9KykL7b43GnbY9vj+/fvdxQPfaDXNk3b69raWu/ZsDNTD7XtxyS9L+n1iPhFsxFxLiJGETE6cOBAlxlREL22aSe9zs3N9R8QOzLVUNue1Ubpb0fEB2UjoS/02iZ6bc80r/qwpLckrUTEm+UjoQ/02iZ6bdM0V9TPS1qU9ILtryZvLxbOhfLotU302qBtX54XEZ9J6uwPaSIHem0TvbaJn0wEgOQYagBIjqEGgOQYagBIjqEGgOQYagBIjqEGgOQYagBIjqEGgOQYagBIjqEGgOQcEd0f1P63pH/t4hC/lXSrozh7OcPvI+J3XYWh1zQZ6LXNDA/stchQ75btcUSMyFA/Q5cyPB8ydC/D82k9A7c+ACA5hhoAkss61OdqBxAZSsjwfMjQvQzPp+kMKe9RAwD+J+sVNQBggqEGgORSDbXtk7a/tn3d9huVMpy3/YPtq5XOf8T2J7ZXbF+z/VqNHF2r3S29lrHXe51kKN9tRKR4k7RP0j8l/UHSfkl/k3SsQo4/SnpO0tVKX4cnJD03ef9xSf+o8XVorVt6pddHudtMV9QLkq5HxDcR8bOkdyW91HeIiPhU0o99n3fT+b+PiCuT93+StCJpWCtPR6p3S69F7PleJxmKd5tpqIeSvt30eFWP/n/kXbE9L+lZSV9UjrJbdLsJvbarVLeZhtpbfGzPvnbQ9mOS3pf0ekSs1c6zS3Q7Qa/tKtltpqFelXRk0+MnJX1XKUtVtme1UfjbEfFB7TwdoFvRa8tKd5tpqL+U9LTtp2zvl/SypA8rZ+qdbUt6S9JKRLxZO09H9ny39NquPrpNM9QRsS5pSdLH2rgZ/15EXOs7h+13JH0u6Rnbq7Zf7TnC85IWJb1g+6vJ24s9Z+hUhm7ptXv0+l/Fu+VHyAEguTRX1ACArTHUAJAcQw0AyTHUAJAcQw0AyTHUAJAcQw0Ayf0HTDUCBioy01YAAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 432x288 with 3 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "# print(\"imag:\\n\", image)\n",
    "print(\"image.shape\", image.shape)\n",
    "\n",
    "weight = tf.constant([[[[1.,10.,-1.]],[[1.,10.,-1.]]],\n",
    "                      [[[1.,10.,-1.]],[[1.,10.,-1.]]]])\n",
    "print(\"weight.shape\", weight.shape)\n",
    "conv2d = tf.nn.conv2d(image, weight, strides=[1, 1, 1, 1], padding='SAME')\n",
    "conv2d_img = conv2d.eval()\n",
    "print(\"conv2d_img.shape\", conv2d_img.shape)\n",
    "conv2d_img = np.swapaxes(conv2d_img, 0, 3)\n",
    "for i, one_img in enumerate(conv2d_img):\n",
    "    print(one_img.reshape(3,3))\n",
    "    plt.subplot(1,3,i+1), plt.imshow(one_img.reshape(3,3), cmap='gray')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### MAX POOLING\n",
    "\n",
    "\n",
    "<img width=\"1034\" alt=\"스크린샷 2022-08-18 오전 8 09 01\" src=\"https://user-images.githubusercontent.com/91893721/185259146-dca50751-3c8c-4252-96ec-cfc7b8016b75.png\">\n",
    "\n",
    "<img width=\"1071\" alt=\"스크린샷 2022-08-18 오전 8 09 26\" src=\"https://user-images.githubusercontent.com/91893721/185259190-769523ac-1dd8-4c70-9627-2efdedef9a0f.png\">"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /var/folders/fj/y92l0p5x6d9030lr98_z9d2r0000gn/T/ipykernel_17665/3454378227.py:3: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.\n",
      "\n",
      "(1, 1, 1, 1)\n",
      "[[[[4.]]]]\n"
     ]
    }
   ],
   "source": [
    "image = np.array([[[[4],[3]],\n",
    "                    [[2],[1]]]], dtype=np.float32)\n",
    "pool = tf.nn.max_pool(image, ksize=[1, 2, 2, 1],\n",
    "                    strides=[1, 1, 1, 1], padding='VALID')\n",
    "print(pool.shape)\n",
    "print(pool.eval())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### SAME: Zero paddings\n",
    "\n",
    "<img width=\"1056\" alt=\"스크린샷 2022-08-18 오전 8 10 08\" src=\"https://user-images.githubusercontent.com/91893721/185259284-45b66582-3886-4565-ba19-5503cc02fce8.png\">\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1, 2, 2, 1)\n",
      "[[[[4.]\n",
      "   [3.]]\n",
      "\n",
      "  [[2.]\n",
      "   [1.]]]]\n"
     ]
    }
   ],
   "source": [
    "image = np.array([[[[4],[3]],\n",
    "                    [[2],[1]]]], dtype=np.float32)\n",
    "pool = tf.nn.max_pool(image, ksize=[1, 2, 2, 1],\n",
    "                    strides=[1, 1, 1, 1], padding='SAME')\n",
    "print(pool.shape)\n",
    "print(pool.eval())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/fj/y92l0p5x6d9030lr98_z9d2r0000gn/T/ipykernel_17665/426799966.py\", line 1, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
      "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/__init__.py\", line 39, in <module>\n",
      "    from tensorflow.contrib import compiler\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/compiler/__init__.py\", line 21, in <module>\n",
      "    from tensorflow.contrib.compiler import jit\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/compiler/__init__.py\", line 22, in <module>\n",
      "    from tensorflow.contrib.compiler import xla\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/compiler/xla.py\", line 22, in <module>\n",
      "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/python/estimator/model_fn.py\", line 26, in <module>\n",
      "    from tensorflow_estimator.python.estimator import model_fn\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
      "    from tensorflow_estimator._api.v1 import estimator\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
      "    from tensorflow_estimator._api.v1.estimator import experimental\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
      "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 27, in <module>\n",
      "    from tensorflow_estimator.python.estimator import estimator\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 36, in <module>\n",
      "    from tensorflow.python.profiler import trace\n",
      "ImportError: cannot import name 'trace' from 'tensorflow.python.profiler' (/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/python/profiler/__init__.py)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 1495, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 1453, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/fj/y92l0p5x6d9030lr98_z9d2r0000gn/T/ipykernel_17665/426799966.py\", line 1, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
      "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/__init__.py\", line 39, in <module>\n",
      "    from tensorflow.contrib import compiler\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/compiler/__init__.py\", line 21, in <module>\n",
      "    from tensorflow.contrib.compiler import jit\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/compiler/__init__.py\", line 22, in <module>\n",
      "    from tensorflow.contrib.compiler import xla\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/compiler/xla.py\", line 22, in <module>\n",
      "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/python/estimator/model_fn.py\", line 26, in <module>\n",
      "    from tensorflow_estimator.python.estimator import model_fn\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
      "    from tensorflow_estimator._api.v1 import estimator\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
      "    from tensorflow_estimator._api.v1.estimator import experimental\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
      "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 27, in <module>\n",
      "    from tensorflow_estimator.python.estimator import estimator\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 36, in <module>\n",
      "    from tensorflow.python.profiler import trace\n",
      "ImportError: cannot import name 'trace' from 'tensorflow.python.profiler' (/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/python/profiler/__init__.py)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3474, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 1495, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 1453, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/fj/y92l0p5x6d9030lr98_z9d2r0000gn/T/ipykernel_17665/426799966.py\", line 1, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
      "    from tensorflow.examples.tutorials.mnist import input_data\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
      "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/__init__.py\", line 39, in <module>\n",
      "    from tensorflow.contrib import compiler\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/compiler/__init__.py\", line 21, in <module>\n",
      "    from tensorflow.contrib.compiler import jit\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/compiler/__init__.py\", line 22, in <module>\n",
      "    from tensorflow.contrib.compiler import xla\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/contrib/compiler/xla.py\", line 22, in <module>\n",
      "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/python/estimator/model_fn.py\", line 26, in <module>\n",
      "    from tensorflow_estimator.python.estimator import model_fn\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
      "    from tensorflow_estimator._api.v1 import estimator\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
      "    from tensorflow_estimator._api.v1.estimator import experimental\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
      "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 27, in <module>\n",
      "    from tensorflow_estimator.python.estimator import estimator\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 36, in <module>\n",
      "    from tensorflow.python.profiler import trace\n",
      "ImportError: cannot import name 'trace' from 'tensorflow.python.profiler' (/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow_core/python/profiler/__init__.py)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3474, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3396, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 1495, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 1453, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "from tensorflow.examples.tutorials.mnist import input_data\n",
    "mnist = input_data.read_data_sets(\"MNIST_data/\", one_hot=True)\n",
    "# Check out https://www.tensorflow.org/get_started/mnist/beginners for\n",
    "# more information about the mnist dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "img = mnist.train.images[0].reshape(28,28)\n",
    "plt.imshow(img, cmap='gray')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "sess = tf.InteractiveSession()\n",
    "\n",
    "img = img.reshape(-1,28,28,1)\n",
    "W1 = tf.Variable(tf.random_normal([3, 3, 1, 5], stddev=0.01))\n",
    "conv2d = tf.nn.conv2d(img, W1, strides=[1, 2, 2, 1], padding='SAME')\n",
    "print(conv2d)\n",
    "sess.run(tf.global_variables_initializer())\n",
    "conv2d_img = conv2d.eval()\n",
    "conv2d_img = np.swapaxes(conv2d_img, 0, 3)\n",
    "for i, one_img in enumerate(conv2d_img):\n",
    "    plt.subplot(1,5,i+1), plt.imshow(one_img.reshape(14,14), cmap='gray')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pool = tf.nn.max_pool(conv2d, ksize=[1, 2, 2, 1], strides=[\n",
    "                        1, 2, 2, 1], padding='SAME')\n",
    "print(pool)\n",
    "sess.run(tf.global_variables_initializer())\n",
    "pool_img = pool.eval()\n",
    "pool_img = np.swapaxes(pool_img, 0, 3)\n",
    "for i, one_img in enumerate(pool_img):\n",
    "    plt.subplot(1,5,i+1), plt.imshow(one_img.reshape(7, 7), cmap='gray')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.7.0 ('test2')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "3a129cd62a9a0696987b02b9aa02558856d3df1fbe04ae6225da87b58ee16246"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
